name: CI/CD for Node.js App

on:
   push:
    branches: [ "main" ] # Trigger on pushes to the main branch
   pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Node.js Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
     # Step 3: Clear npm cache
      - name: Clear npm cache
        run: npm cache clean --force   
      # - run: npm ci    

     # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Build the app
      - name: Build the App
        run: npm run build --if-present

       # Step 6:  Run Format
      - name: Run Format
        run: npm run format --if-present  

       # Step 7: Run Lint
      - name: Run Lint
        run: npm run lint --if-present  

      # Step 8: Run Tests
      # - name: Run Tests
      #   run: npm test
